.class public final Lop0/l$a$i;
.super Lep0/u;
.source "SourceFile"

# interfaces
.implements Ldp0/a;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lop0/l$a;-><init>(Lop0/l;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lep0/u;",
        "Ldp0/a<",
        "Lup0/e;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic b:Lop0/l;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lop0/l<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lop0/l;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lop0/l<",
            "TT;>;)V"
        }
    .end annotation

    iput-object p1, p0, Lop0/l$a$i;->b:Lop0/l;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lep0/u;-><init>(I)V

    return-void
.end method


# virtual methods
.method public final invoke()Ljava/lang/Object;
    .locals 4

    .line 1
    iget-object v0, p0, Lop0/l$a$i;->b:Lop0/l;

    sget v1, Lop0/l;->g:I

    .line 2
    invoke-virtual {v0}, Lop0/l;->y()Lsq0/b;

    move-result-object v0

    .line 3
    iget-object v1, p0, Lop0/l$a$i;->b:Lop0/l;

    .line 4
    iget-object v1, v1, Lop0/l;->f:Lop0/k0$b;

    .line 5
    invoke-virtual {v1}, Lop0/k0$b;->invoke()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lop0/l$a;

    .line 6
    iget-object v1, v1, Lop0/o$b;->a:Lop0/k0$a;

    sget-object v2, Lop0/o$b;->b:[Llp0/l;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    .line 7
    invoke-virtual {v1}, Lop0/k0$a;->invoke()Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<get-moduleData>(...)"

    .line 8
    invoke-static {v1, v2}, Lep0/s;->g(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, Lzp0/h;

    .line 9
    iget-boolean v2, v0, Lsq0/b;->c:Z

    if-eqz v2, :cond_0

    .line 10
    iget-object v1, v1, Lzp0/h;->a:Lfr0/j;

    .line 11
    invoke-virtual {v1, v0}, Lfr0/j;->b(Lsq0/b;)Lup0/e;

    move-result-object v0

    goto :goto_0

    .line 12
    :cond_0
    iget-object v1, v1, Lzp0/h;->a:Lfr0/j;

    .line 13
    iget-object v1, v1, Lfr0/j;->b:Lup0/c0;

    .line 14
    invoke-static {v1, v0}, Lup0/u;->a(Lup0/c0;Lsq0/b;)Lup0/e;

    move-result-object v0

    :goto_0
    if-nez v0, :cond_3

    .line 15
    iget-object v0, p0, Lop0/l$a$i;->b:Lop0/l;

    .line 16
    invoke-static {v0}, Ljava/util/Objects;->requireNonNull(Ljava/lang/Object;)Ljava/lang/Object;

    .line 17
    sget-object v1, Lzp0/d;->c:Lzp0/d$a;

    .line 18
    iget-object v2, v0, Lop0/l;->e:Ljava/lang/Class;

    .line 19
    invoke-virtual {v1, v2}, Lzp0/d$a;->a(Ljava/lang/Class;)Lzp0/d;

    move-result-object v1

    if-eqz v1, :cond_1

    .line 20
    iget-object v1, v1, Lzp0/d;->b:Lmq0/a;

    if-eqz v1, :cond_1

    .line 21
    iget-object v1, v1, Lmq0/a;->a:Lmq0/a$a;

    goto :goto_1

    :cond_1
    const/4 v1, 0x0

    :goto_1
    if-nez v1, :cond_2

    const/4 v2, -0x1

    goto :goto_2

    .line 22
    :cond_2
    sget-object v2, Lop0/l$b;->a:[I

    invoke-virtual {v1}, Ljava/lang/Enum;->ordinal()I

    move-result v3

    aget v2, v2, v3

    :goto_2
    packed-switch v2, :pswitch_data_0

    .line 23
    :pswitch_0
    new-instance v0, Lro0/k;

    invoke-direct {v0}, Lro0/k;-><init>()V

    throw v0

    .line 24
    :pswitch_1
    new-instance v2, Lop0/i0;

    const-string v3, "Unknown class: "

    .line 25
    invoke-static {v3}, La/a;->c(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v3

    .line 26
    iget-object v0, v0, Lop0/l;->e:Ljava/lang/Class;

    .line 27
    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string v0, " (kind = "

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 v0, 0x29

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v2, v0}, Lop0/i0;-><init>(Ljava/lang/String;)V

    throw v2

    .line 28
    :pswitch_2
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "

    .line 29
    invoke-static {v2}, La/a;->c(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 30
    iget-object v0, v0, Lop0/l;->e:Ljava/lang/Class;

    .line 31
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 32
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 33
    :pswitch_3
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "

    .line 34
    invoke-static {v2}, La/a;->c(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 35
    iget-object v0, v0, Lop0/l;->e:Ljava/lang/Class;

    .line 36
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 37
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 38
    :pswitch_4
    new-instance v1, Lop0/i0;

    const-string v2, "Unresolved class: "

    .line 39
    invoke-static {v2}, La/a;->c(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 40
    iget-object v0, v0, Lop0/l;->e:Ljava/lang/Class;

    .line 41
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v1, v0}, Lop0/i0;-><init>(Ljava/lang/String;)V

    throw v1

    :cond_3
    return-object v0

    nop

    :pswitch_data_0
    .packed-switch -0x1
        :pswitch_4
        :pswitch_0
        :pswitch_3
        :pswitch_3
        :pswitch_3
        :pswitch_2
        :pswitch_1
        :pswitch_4
    .end packed-switch
.end method
